biosustain/Maud

- setup.cfg
- setup.py
- src/maud/cli.py
- src/maud/code_generation.py
- tests/test_unit/test_code_generation.py
This pr fixes a few bugs that I ran into while preparing a demo. It also adds a call to the cmdstan `diagnose` function after sampling - this used to happen automatically and should help us to catch problematic models.
First, there is a problem with the Haldane code generation where some `Keq`s should be `delta_g`s.
Second, there is a stray `]` in an ordered unibi template.
Finally, there are some leftover references to the old apache license in `setup.cfg`.
> Fix incorrect license, haldane line function, typo and add diagnostic check after sampling

- README.rst
- docs/usage/installation.rst
A small change to the installation instructions - this method is a bit shorter and doesn't require ssh access.
> Doc: update docs with latest recommended installation method

- data/in/linear.toml
- src/maud/code_generation.py
- src/maud/io.py
- src/maud/stan_code/allostery.stan
- src/maud/stan_code/big_k_rate_equations.stan
- src/maud/stan_code/modular_rate_law.stan
- tests/test_unit/test_code_generation.py
Adding positive allostery and competitive inhibition (for modular rate law only) as a feature to Maud. Positive allostery is integrated into the MWC framework. There is an example in the `data/in/linear.toml` file about how both mechanisms can be used. As a summary, all it requires is an allosteric_activators/competitive_inhibitors field in the reaction.enzymes section, like with the following example:
[[reactions.enzymes]]
id = 'r1'
name = 'the enzyme that catalyses reaction r1'
mechanism = 'uniuni'
allosteric_activators = ['M2']
competitive_inhibitors = ['M1']
and in the parameters section it requires 1 transfer constant for each reaction that has allostery, regardless of how many allosteric inhibitors/activators and must be specified with the following format:
{ target_id = …
> Pos neg allostery

- .gitignore
- data/out/readme.md
- data/stan_records/readme.md
- src/maud/cli.py
- src/maud/sampling.py
This change removes the folders `data/out` and `data/stan_records` and sends the output of `maud sample` to the current directory, or a directory of the user's choice if they use the `--output_dir` option.
The reason for making this change is to make it possible to use Maud without changing directory to wherever it is installed. After this change it should be possible to start using Maud by just doing
```
pip install https://github.com/biosustain/Maud/archive/master.zip
maud sample path/to/data.toml
```
> Put output data in the same file that maud sample was run from

- data/in/linear.toml
- data/in/yeast.toml
- src/maud/io.py
- src/maud/sampling.py
- src/maud/stan_code/inference_model_lower_blocks.stan
- src/maud/validation.py
- tests/data/linear.stan
- tests/data/linear.toml
- tests/test_unit/test_sampling.py
This pull request changes the way that Maud handles unbalanced metabolite and enzyme concentration measurements, making them use the same method we use for flux and balanced metabolite concentration measurements.
At present Maud treats flux and balanced metabolite measurements using standard measurement models: the measured values are treated as noisy draws from distributions centred on a latent true value. Unbalanced metabolite and enzyme concentration measurements, on the other hand, are treated as directly specifying prior distributions for these unknowns. There are a few problems with this setup:
- There's no principled reason to use two different setups and it's a bit confusing for different kinds of measurement to be treated differently when the measurement process itself is …
> Model all measurements in the same way

- src/maud/code_generation.py
- src/maud/data_model.py
- src/maud/io.py
- src/maud/sampling.py
- src/maud/validation.py
Maud's data universe needs to include metabolites-in-compartments in order to handle e.g. internal vs external glucose. It also has to include non-compartmentalised metabolites in order to properly handle transport reactions' thermodynamics - unless we tell the model that internal and external glucose are the same, we risk allowing them to have different formation energies.
The current implementation handles both metabolites and metabolites-in-compartments, but does so implicitly. The `Metabolite` class really represents metabolites-in-compartments, and there is a bit of logic determining which of these are really the same substance. This is a bit confusing and the code that sets Stan codes for these things gets hard to follow. 
This pull request changes Maud's data model so that it has …
> Refactor: explicitly distinguish metabolites and metabolites-in-compartments

- setup.cfg
- src/maud/cli.py
- src/maud/sampling.py
This change fixes an annoying bug was causing Maud to throw an error the first time it ran after the stan source code was changed. 
It turned out that a `.hpp` file that should have been deleted wasn't, causing cmdstanpy to think there was no need to create a new one and resulting in the error.
This change removes the executable, `.hpp` and `.o` file for a model (if they exist) in advance whenever there is a need to recompile. This fixed the bug for me.
I've also added a change to the `setup.cfg` file that should ensure that the latest version of cmdstanpy is installed, and fixed a couple of things that the new version broke (the file saving mechanism changed a bit).
> Update cmdstanpy and fix compilation bug

- src/maud/code_generation.py
- src/maud/data_model.py
- src/maud/io.py
- src/maud/sampling.py
- src/maud/stan_code/inference_model_lower_blocks.stan
- tests/data/linear.json
- tests/data/linear.stan
- tests/test_unit/test_io.py
- tests/test_unit/test_sampling.py
This change improves the process of passing indexes to Stan, sets better initial values for unbalanced metabolite concentration parameters and tidies up the tests a little.
Stan indexes are now created once when the MaudInput object is loaded using the new `get_stan_codes`. The modules that need stan codes now load them rather than recalculating them. This makes it less likely that they will disagree, which it turns out is happening at the moment.
Initial values for unbalanced metabolite concentrations are now set to measured values where these are available. This resulted in much higher joint log probability for the yeast model. For external glucose the measurement was about 73 and the initial value was 0.1 (and the posterior is probably quite hard to explore with all the non-linear …
> More reliable indexing

- docs/adr/0010-modular-rate-law-only.md
- src/maud/code_generation.py
- tests/data/linear.stan
- tests/test_unit/test_code_generation.py
This change gets rid of support for non-modular rate laws, which aren't being used in the models we are actively developing. 
The aim is to make the `code_generation.py` module easier to understand, and to make it easier to refactor the code generation logic without having to worry about having to worry about breaking these mechanisms.
I've added an adr document explaining the rationale in a bit more detail. I've put the status as 'accepted' but that is on the assumption that it passes code review. If you disagree with the change feel free to reject or discuss!
> Remove non-modular rate laws

- src/maud/cli.py
- src/maud/data_model.py
- src/maud/sampling.py
- src/maud/stan_code/steady_state_function.stan
- tests/data/linear.stan
The argument types for integrate_ode_bdf were updated in cmdstan 2.22.1. This PR addresses this problem and should work using the new cmdstan. Unsure if it will work with the previous cmdstan. However you have to delete the old one first, it's typically located in ~/.cmdstanpy. You can delete this and run the install_cmdstan command in your repository after installing the python packages specified in the repository. Just follow the install instructions and it'll work
> Update steady state arguments

- .travis.yml
This change adds cmdstan installation to the install step of the travis build so that we can properly test model compilation and sampling
> test: make travis install cmdstan before running tox

- src/maud/cli.py
- src/maud/sampling.py
- src/maud/stan_code/functions_block.stan
- src/maud/stan_code/inference_model_lower_blocks.stan
- src/maud/stan_code/partial_sums.stan
- tests/data/linear.stan
- tests/test_integration/test_pipeline.py
Uses Stan's new `reduce_sum` function to parallelise the likelihood if possible. 
This should hopefully speed the model up a bit but to verify this we'll need to try it out on a computer with lots of cores.
> Parallelise likelihood with reduce_sum

- docs/theory/statistics.rst
- src/maud/cli.py
- src/maud/sampling.py
- src/maud/utils.py
- tests/test_integration/test_pipeline.py
- tests/test_unit/test_utils.py
This change explains what statistical model Maud is trying to implement as part of #228. 
To review you probably want to build the docs locally by running `make html` from the `docs` folder, then open the file `docs/_build/html/index.html` with a web browswer. If you haven't already done so you'll need to run `pip install -e .[development]` to install all the dependencies required to build the documentation.
When I got to the bit about how priors should be set I realised that the recommended method of setting the prior location and scale parameters based on quantiles is a bit hard to implement, so I bundled in some helper functions that make it easier.
> Doc: document Maud's statistical model, add new helper functions

- scripts/plot_samples.py
- setup.cfg
- src/maud/plot_samples.py
- tests/test_unit/test_utils.py
This is a tool to help plot your posterior draws. It's fairly basic at the moment and doesn't spit out the prettiest plots but is 99% automated only requiring the following inputs which are noted in the documentation:
* TOML file directory (relative to Maud home directory)
* CSV file directory (relative to Maud home directory)
* model name
* csv timestamp code
The current output plots are:
* concentrations
* fluxes
* enzyme concentrations
* formation energies
* Keqs
* kcats
* Kms
* feat: automated plotting of population
* style: fixing black style guide
* Docs: update dependencies for plotting using plotnine
There are several features not implemented that will be once a finalised file structure is resolved:
* overlaying measured/prior values with CIs
* prettier plots in general
> Automated plotting

- tests/test_integration/test_pipeline.py
The pipeline test runs through all of the Maud workflow from input to sampling. An issue previously encountered was the compatibility with cmdstanpy and/or arviz, which like to change their functions a lot. This PR removes a lot of the reliance using a dictionary to specify the 90% CI, and converting the fit object to a dataframe. There is no reliance on Arviz and the test should now be robust to additional parameters introduced into the Stan program. For example:
* Transformed Gibbs Energies,
* Transformed Kinetic Parameters,
* Enzyme specific fluxes.
* test: using dataframes to compare test results
* style: satisfying black style guide
* bug: resetting warmup and sampling iterations
* style: removing unnecessary code
> Robust test

- scripts/run_ecoli_simulation_study.py
- src/maud/inference_model.stan
- src/maud/io.py
- src/maud/sampling.py
- tests/data/ecoli_small.toml
This change alters the Stan model so that all the non-transformed parameters are auxiliaries with standard normal distributions, with the meaningful parameters derived from these by shifting and scaling according to the priors.
There are two main reasons for doing this:
1) Performance. Stan generally prefers to work with numbers around unit scale. This should make life a little easier for the adaptation algorithm, as the correlations and differences in scale between the auxiliary parameters should be simpler and more consistent than between the meaningful ones.
2) Interpretability. A lot of the work with Maud going forward will involve trying to understand why the sampler behaves as it does, so as to improve performance by reparameterisation. It should be easier to inspect the auxiliary …
> Rescale params

- Makefile
Adds a new makefile command `clean-stan` which removes the binary, `.hpp` and `.o` files if they are present. This is just for convenience when a developer wants to recompile the main model.
> Feat: makefile command for removing auxiliary Stan files

- .github/workflows/python-app.yml
- .github/workflows/run_tests.yml
- .travis.yml
Our plan on Travis CI apparently has a limited number of computer minutes, which we [just passed](https://travis-ci.com/organizations/biosustain/plan/usage). This change switches us to github actions for CI, which avoids the problem.
> Migrate to GitHub actions

- .github/pull_request_template.md
- .github/workflows/run_integration_tests.yml
- .github/workflows/run_tox.yml
- tox.ini
A few commits aimed at improving the process with automatic tests. 
At the moment running `tox` triggers our integration tests, which take quite a long time to run. We should definitely run the integration tests before merging a pr, but it's annoying to spend ages waiting for them to run after every single push. 
This change makes `tox` only run the unit tests. Integration tests can be run locally with `pytest tests/test_integration` or with github actions using a new manual workflow. I've also added the following checklist to make sure we don't forget to run the new workflow:
Checklist:
> Streamline automatic testing

- README.rst
- docs/usage/installation.rst
Updated the instructions for installing Maud on windows - this is what worked for Areti. 
If these instructions work for others, this should address issue #257.
Checklist:
> Windows installation instructions

- src/maud/modular_rate_law.stan
This caused an error for @areti1906: Stan's `size` function doesn't work on vectors. This change switches to the `rows` function, which does work for vectors.
Mysteriously I don't seem to get the same problem, but I guess who cares once it's fixed!
> Bug: change size to rows for vectors in Stan code

- docs/adr/0016-validating-measured-fluxes.md
- setup.cfg
- src/maud/sampling.py
- src/maud/utils.py
Summary
Including a warning to the user about potentially under and over specified flux networks. This check is based on the stoichiometric matrix and DOF. It’s up to the user to determine if the fluxes are independent, for examples, measuring the input and output flux of a linear pathway would be 2 independent measurements. However, taking a single measurement and inferring the output flux and using that as a measurement is not independent.
Commits
feat: calculating null and rref
feat: identifying undefined DOF and overspecified systems
tests: satisfying style guides
feat: including sympy in setup config
adr: including the decision on validating the measured fluxes
doc: adding doc strings
Checklist:
Updated any relevant documentation
Add an adr doc if appropriate
Include links to any …
> Check measured fluxes

- src/maud/io.py
I think some of our models have been going wrong lately because the priors for drains have been set incorrectly, assuming a lognormal rather than a normal distribution.
This fix ensures they are in the list of parameters that are given normal priors. 
Checklist:
> Bug fix: drain priors are wrong

- src/maud/analysis.py
- src/maud/cli.py
- src/maud/get_prior_template.py
- src/maud/user_templates.py
- tests/data/example_features/drain/kinetic_model.toml
- tests/data/example_features/michaelis_menten/kinetic_model.toml
- tests/data/example_features/one_allosteric_modifier/kinetic_model.toml
- tests/data/example_features/phosphorylation/kinetic_model.toml
- tests/data/example_features/two_allosteric_modifiers/kinetic_model.toml
inits can now be generated and used in Maud through the command `maud generate-inits <data_path> --chain=<chain_number (Python Indexing)> --draw=<draw_number (Python Indexing)> --warmup=<warmup phase=1 or sampling phase=0>`. This will then generate an inits file to use for initialising samples and tuning ODE solvers.
Initial conditions are extremely useful for many conditions. Tuning the ODE parameters cannot be done far away from the typical set because these systems typically blow up and aren'y representative of the systems you want to sample on. Therefore, using an initial value to tune the ODE parameters is extremely beneficial. Furthermore, initialising your sampling around a point makes the warmup phase more robust, as it doesn't have to travel as far to find the typical set. …
> Generate init from run

- src/maud/model.stan
updating the steady state evaluation so it's independent of the absolute scale of the metabolites. evaluates it 10 seconds in the future and checks if the sum of relative metabolite changes is less than 0.001 of that.
Checklist:
> feat: changing steady state evaluation to relative

- src/maud/sampling.py
The latest cmdstanpy version replaced the function `jsondump` with `write_stan_json`. This change keeps us up to date. I had to change to the standard `json.dump` for the coords dictionary as the new function enforces Stan compatibility.
Checklist:
> Bug: replace obsolete jsondump calls

- pyproject.toml
- src/maud/analysis.py
I hit an error in the demo notebook because of a library called Numba. Arviz tries to use it for a speedup if it's installed, but sometimes it seems to cause an error. This change fixed it on my computer.
Checklist:
> Bug: make arviz disable numba when loading InferenceData

- src/maud/io.py
- src/maud/model.stan
I found this quite big bug while preparing the demo notebook for the workshop - it might explain if any complicated models have been a bit off recently!
I also bundled a second bugfix that was causing an error when trying to set 2D priors using percentiles. I just copied the equivalent line from the function `extract_1d_prior`.
Checklist:
> Bug: fix wrong index in enzyme concentration likelihood function

- src/maud/io.py
Given a multivariate specification, the MultiVariateNormalPrior1d data type is not specified in the get_inits() function. This fixes that.
Checklist:
> bug: make defining inits possible for multivariate dgf

- scripts/get_dgf_priors_from_equilibrator.py
This change fixes a bug in the script for fetching dgf priors from equilibrator: currently the call to `load_maud_input_from_toml` is missing the `mode` argument.
Checklist:
> Bug: add missing "sample" argument to function call in dgf script

- src/maud/io.py
Fixes a bug that @ShannaraTP found: if `config.toml` specifies some dgf prior files that don't yet exist, the script `get_dgf_priors_from_equilibrator.py` fails. The fix is to change `io.py` so that instead of checking if the files are specified in `config.toml`, it instead checks whether they exist.
Checklist:
> Bug: make dgf script work with specified but non-existing csvs

- setup.cfg
This should hopefully fix issue #371. The bug was fixed in cmdstanpy but hasn't been released yet (see https://github.com/stan-dev/cmdstanpy/pull/507). The easiest fix seemed like installing the latest cmdstanpy for now. Once a version of cmdstanpy without this bug is released we can change again to installing from pyPI
Checklist:
> Install cmdstan from github develop branch

- src/maud/analysis.py
- src/maud/out_of_sample_model.stan
Summary:
Including regulatory decompositions for out-of-sample predictions
Checklist:
> feat: including regulatory decompositions in out-of-sample predictions

- src/maud/functions.stan
- src/maud/model.stan
- src/maud/out_of_sample_model.stan
I changed the Stan code that checks if the system is in a steady state. Instead of doing an extra 10 second simulation, we now just calculate S times v for the balanced metabolites-in-compartments and do both a relative and absolute check for being close to zero.
The immediate reason for doing this is that the current purely relative check doesn't work for metabolites with high concentrations - they can still be accumulating even when the relative change over 10 seconds isn't very big. @ShannaraTP hit this problem in an AAA model.
Checklist:
> Improved steady state checking

- src/maud/cli.py
- src/maud/data_model.py
- src/maud/io.py
- src/maud/model.stan
- src/maud/sampling.py
This change adds a new command `maud variational` which runs variational inference via the cmdstanpy method `CmdStanModel.variational`. Arguments can be configured in the config file in the table `variational_options`.
Variational inference could potentially be useful for getting results quicker than MCMC when we know it is sure to work, and also for finding a good parameter configuration to initialise the MCMC.
I also added the possibility to customise how the underlying Stan model is compiled to c++, through the CmdStanModel instantiation arguments `stanc_options` and `cpp_options`. These each get their own optional tables in the config file. Lists of possible options can be found [here](https://mc-stan.org/docs/2_29/stan-users-guide/stanc-args.html) and …
> Variational inference and setting stanc and c++ options

- .github/workflows/release.yml
- README.rst
- docs/usage/contributing.rst
- docs/usage/installation.rst
- setup.cfg
This change adds a github workflow that should create a new release of maud on pypi every time a git tag starting with 'v' is pushed. This fixes issue #27.
I have done the necessary clicking and typing to put maud on PyPI under the name 'maud-metabolic-models' (`pip install maud-metabolic-models` now works!), but I haven't tested the github action yet as I have no idea how to do that! I'll have a go when this pr is merged.
Checklist:
> Feat: Workflow for releasing new versions of maud and setup.cfg fix

- scripts/export-yaml.py
- src/maud/data_model/stan_variable_set.py
- src/maud/getting_stan_variables.py
- src/maud/parsing_measurements.py
Jorge found a [problem](https://github.com/biosustain/maudtools/pull/15#pullrequestreview-1042997760) in maudtools that I think is caused by an upstream bug in Maud: the `ConcUnbalanced` Stan variable should have existing `split_ids` because it is partly identified by metabolite-in-compartments, which in turn have split ids.
This change fixes `ConcUnbalanced` and also adds a new validation to check that any Stan variable with non-trivial id components has split ids.
Checklist:
> Bug: Fix unbalanced mic concentration stan variable and validate

- setup.cfg
Pydantic 1.10 is making the type validation fail for `split_ids` at least for kcats, whereas it worked fine for pydantic 1.9.
A dependency (netCDF4) of arviz is also making it fail.
I have pinned netCDF4, arviz and pydantic.
Checklist:
- [] Include links to any relevant issues in the description
> chore: pin arviz and pydantic deps

- src/maud/data_model/stan_variable_set.py
- src/maud/getting_stan_variables.py
Indexing parameters in Maud will be more consistent as we only need to refer to the id_components and split_ids.
Checklist:
> including split ids

- setup.cfg
- src/maud/data/example_outputs/linear/user_input/config.toml
- src/maud/data/example_outputs/linear/user_input/experiments.toml
- src/maud/data/example_outputs/linear/user_input/kinetic_model.toml
- src/maud/data/example_outputs/linear/user_input/parameters.toml
- src/maud/data/example_outputs/linear/user_input/priors.toml
This change adds an example maud output to Maud's data folder.
I added it to make it easier to test maudtools functions that require a maud output but there are probably some other uses too.
Checklist:
> Feat: example output

- src/maud/data_model/maud_config.py
- src/maud/data_model/maud_input.py
This change fixes a bug that I encountered on a fresh install of Maud. 
I think pydantic got a bit more pydantic about mutability in a recent release - this changes things to be correct.
Checklist:
> Default factories

- src/maud/stan/model.stan
This change adds information about the values of parameters relative to their prior distributions to the message that Maud prints when there is a steady state failure. This is useful when trying to diagnose whether a failure could be fixed by different priors.
Checklist:
> Feat: print more debug info on steady state failure

- docs/usage/post_installation_usage.rst
- src/maud/cli.py
- src/maud/data_model/maud_config.py
- src/maud/running_stan.py
From the Maud debugging sessions, optimizing the model to get a Maximum A Posteriori (MAP) has revealed as a great way to debug which prior are making the model dysfunctional.
I gathered the [optimize snippet](https://github.com/biosustain/maud-debugging/tree/main/debugging-tools) from @NicholasCowie into a new cli argument `maud optimize [DATA]`.
Nomenclature question: In the docs, I have written "Maximum Likelihood Estimate" but would MAP be more appropriate in the Bayesian sense? Or is it the same? In the `cmdstanpy` docs for `model.optimize()`, they use MLE.
Checklist:
> feat: optimize model

- maud/data_model/maud_parameter.py
- maud/data_model/parameter_set.py
Downstream of #447 
There is some code duplication of Train/Test parameters that we can remove.
This is important in terms of the "development cost of adding a new parameter", probably there are some opportunities for streamlining the `MaudParameter` to `xarray` coords too, but I have not given it a try yet.
Checklist:
> refactor: unify some train/test code

- maud/cli.py
`to_json` on an data object is corrupted possibly by the serialization performed in arviz. To deal with this we will momentarily move to netcdf.
Checklist:
> bug: json rearranges indexes

- maud/cli.py
- maud/running_stan.py
- maud/stan/out_of_sample_model.stan
Predict was previously bugged, this PR fixes this.
Checklist:
> Fix Predict

- .github/workflows/run_tox.yml
- .pre-commit-config.yaml
- docs/getting_started.md
- maud/data/example_inputs/linear_multidgf/config.toml
- maud/data/example_inputs/linear_multidgf/experiments.toml
- maud/data/example_inputs/linear_multidgf/kinetic_model.toml
- maud/data/example_inputs/linear_multidgf/parameters.toml
- maud/data/example_inputs/linear_multidgf/priors.toml
- maud/data_model/maud_input.py
- maud/data_model/maud_parameter.py
- pyproject.toml
- tests/test_unit/test_load_maud_input.py
> Fixed dgf bug

- maud/stan/functions.stan
- maud/stan/model.stan
- maud/stan/out_of_sample_model.stan
`get_allostery` was wrong in the indexing of free enzyme ration, same as vmax was before.
Would be good to have an example with `N_edge` > `N_enzyme` (with drains) to test for this cases.
Checklist:
> Fix indexing on `get_allostery`

- maud/stan/functions.stan
- pyproject.toml
Fixes a pretty big bug in Maud's Stan code: allostery was incorrect for models with isoenzymes because the function `get_allostery` was using the wrong free enzyme ratios.
Checklist:
> Allostery free enzyme ratio bug
