biosustain/Maud

- docs/adr/0012-single-simulation-study.md
Quick document explaining how I plan to implement simulation studies - first I'll make a script that implements a single one, then later on I'll try and generalise it.
> Document plan for implementing a single simulation study.

- scripts/run_ecoli_simulation_study.py
- src/maud/data_model.py
- src/maud/io.py
- src/maud/sampling.py
- src/maud/simulation_study.py
The previous PR worked on the example case, however, this didn't include any isoenzymes and used an incorrect S matrix. This fixes this by creating an S matrix using only reactions and metabolites_in_compartment rather than enzymes and metabolites_in_compartment.
* bug: change to rxn S matrix rather than enz
* style: satisfying qa style guide
Checklist:
There were no changes to any functions that would affect Mauds operation
> Fix flux checking

- src/maud/analysis.py
Inluding warmups in the info object. This is useful for on-line monitoring of sample performance.
Checklist:
> feat: including warmups in infd object

- scripts/plot_samples.py
- tox.ini
This script wasn't working - the fix is pretty easy as we already have a `load_infd` function that it wasn't using.
I tested locally and the plots were created as expected.
Checklist (mostly not applicable as the change is to a script rather than Maud's source code):
> Bug: fix bug in plotting script by using load_infd function

- src/maud/sampling.py
Fixes #330, which turned out to be an issue with the data structure that jsondump accepts.
Checklist:
> Bug: fixed error message from jsondump in sampling.py

- scripts/plot_samples.py
> chore: changing keq such that it's log scale on the plot

- src/maud/functions.stan
I thought this would be a better thing to look for as the total change could be zero despite some concentrations being non-steady
Checklist:
> Bug: make steady state check look for max concentration change

- docs/case_studies/ecoli.rst
- docs/usage/post_installation_usage.rst
I spotted that the case study in the documentation is a bit out of date - this change makes it compatible with Maud's current format.
Checklist:
> Case study doc update

- scripts/plot_samples.py
Updating the plotting script so it includes measurements and confidence intervals on priors.
Checklist:
> Prior confidence intervals

- src/maud/cli.py
Fixes #347, hopefully making it easier to do downstream analysis.
Checklist:
> Save an InferenceData when sampling and simulating

- scripts/get_dgf_priors_from_equilibrator.py
@ShannaraTP hit a bug with the script that fetches formation energy priors from equilibrator. It currently has the wrong order. This PR fixes the bug.
Checklist:
> Bug: fix wrong metabolite order in equilibrator script

- src/maud/functions.stan
- src/maud/io.py
changing the Gibbs energy of water to that used in the equilibrator script and fixing a type check
Checklist:
> Water and small fix

- src/maud/cli.py
- src/maud/data_model/kinetic_model.py
- src/maud/getting_priors.py
I noticed that the simulate command doesn't copy the user input to the output folder - this change fixes that.
Checklist:
> Simulate input bug

- setup.cfg
> Chore: Bump version

- docs/index.rst
> Bug: add contributing page to documentation index

- setup.cfg
- tox.ini
Just a bit of housekeeping
Checklist:
> Chore: remove unused dependencies and fix tox isort warning

- src/maud/data/example_inputs/linear/config.toml
- src/maud/data/example_inputs/methionine/inits.toml
- src/maud/data/example_inputs/methionine/methionine_cycle.toml
While trying to use the methionine example input I noticed a few small errors.
Checklist:
> Bug: fix a few small errors in example inputs

- .github/workflows/build-wheels.yml
> point build-wheels workflow at real PyPI

- pyproject.toml
- tests/test_unit/test_cli.py
This change fixed #429 on my computer.
It also adds a new test that should catch this kind of bug in future.
Checklist:
> Fix missing methionine input

- maud/stan/model.stan
This change fixes a bug that I just released in #449: the priors for fixed formation energy parameters were still being used to calculate the log probability.
Checklist:
> Don't use priors for fixed dgfs

- .gitignore
- docs/inputting.md
- maud/cli.py
- maud/data_model/maud_config.py
- maud/running_stan.py
This change allows users to use the new laplace sampling and pathfinder commands if they want, via the commands `maud laplace` and `maud pathfinder`
Checklist:
> Laplace and pathfinder commands
